### ISSUE TITLE
issues with compiling gistpp

### ISSUE THREAD

**Issue by metma99** [KurtzmanLab/Gist-Post-Processing#1]
Hello:
I am trying to follow your tutorial #25 on ambermd.org and I am at the stage of compiling your gistpp program.
Following your advice using 
`g++ -o gistpp gistpp.cpp gistpp_man.cpp`
I am getting the following warning:

> gistpp.cpp: In member function â€˜dx dx::cat(dx)â€™:
> gistpp.cpp:1392:1: warning: no return statement in function returning non-void [-Wreturn-type]
>  }

Still gistpp is created but when I am running...
`./gistpp`

... the program aborts with the following message:

> ./gistpp: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by ./gistpp)

Short of upating my OS, btw I am running Amber successfully on Centos7, are there any other options to get gistpp to run?

Thank you,
Markus

**Comment by acruzpr** [comment]
Hi Markus,

Clone the git repository an try it again. Im using Centos and I was able to
compile it without errors...

Regards,

Anthony
